### PR TITLE
Adding profile and assets for oculus-touch-v3 (Quest 2) controllers

### PR DESCRIPTION
**Pull request by fe1ixz**
Adds profile and updated assets for the Oculus Quest 2 controllers. @Artyom17 @cabanier requesting approval to merge.

### CODE REVIEW

**Comment by toji** [comment]
Are these the assets @cabanier mentioned in #182?

**Comment by cabanier** [comment]
Yes, would you mind taking a look to make sure that they're acceptable?

**Comment by toji** [comment]
Tested locally, assets appear to be working great! Thank you!

**Comment by cabanier** [comment]
@toji As we discussed, please don't push it to the CDN until we patch the browser.

**Pull request merged**
