### PR TITLE
Added HP Reverb G2 input profile

### PR DESCRIPTION
**Pull request by fordacious**
Adds the input profile for the HP Reverb G2 profile. Falls back to the Oculus Touch.

@toji @Manishearth @thetuvix

### CODE REVIEW

**Comment by Manishearth** [comment]
the hp- prefix doesn't exist yet, we'd need someone from HP to register it on this repo, and then we'd need someone from HP to approve this PR (if I understand the process right). Or they can say they're okay with delegating that to you.

**Comment by toji** [comment]
I'm don't recall if we established that the vendor MUST be the one to register the prefix with the repo, though their input is always appreciated. I wonder if @NellWaliczek is able to pop in and jog our collective memory on what the decision was there. Regardless, though, as the first usage of the `hp` prefix it should also be added to https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/README.md in this PR.

The area where I DO recall that we wanted avoid referencing vendors without their express consent was the fallback profiles. Specifically the fact that this uses `oculus-touch` as a fallback raises an eyebrow, because Oculus may not appreciate non-oculus hardware masquerading as their own. It's not a hard and fast rule, because we have cases like the Samsung Odyssey falling back to the Microsoft WMR controller because they all fall under the WMR umbrella.

**Comment by fordacious** [comment]
I'll add the prefix to the README.md and verify with HP and Oculus people whether or not they approve of this strategy.

**Comment by fordacious** [comment]
Confirmed with Ed Hutchings from Oculus that the Oculus Touch profile is fine to reference as a fallback.

**Comment by toji** [comment]
Seems like you may have missed adding a file in the latest commit?

**Comment by NathanNuberHP** [comment]
Nathan Nuber here from the HP XR team: The team at Microsoft is graciously handling this PR for us. We're good with the 'hp' prefix. Thanks Lachlan and team!

**Comment by toji** [comment]
Thanks Nathan! We appreciate the confirmation!

**Comment by toji** [comment]
Thank you, @fordacious, for following up on this!

**Pull request merged**
