### PR TITLE
potential fix over js modules

### PR DESCRIPTION
**Pull request by himorin**
replaces #255 , incl. missing parts for fix in original PR.

### CODE REVIEW

**Comment by himorin** [comment]
sigh,, check failed... will check later...

**Review by toji — APPROVED** [review]
LGTM. I'm inclined to merge this and see if it's able to deploy correctly. (After all, we're not at risk of being _more_ broken than it is currently, right?) I have a suspicion that the check script is faulty in this regard.

**Comment by toji** [comment]
Let's see how that behaves...

**Comment by toji** [comment]
Yeah, I see it working at https://immersive-web.github.io/webxr-input-profiles/packages/viewer/dist/index.html now as well. Thank you!

**Pull request merged**
