### PR TITLE
Add PicoVR Neo3 controller models and profiles

### PR DESCRIPTION
**Pull request by song-fangzhen**
Pico(Bytedance) would like to contribute the controllers we use to the webxr-input-profiles repo. These models already got acknowledged by @picoxr.

- [x] PicoVR Neo3 controller model and profile

### CODE REVIEW

**Comment by song-fangzhen** [comment]
@Manishearth @toji PTAL, thanks!

**Comment by toji** [comment]
Loaded this locally and it looks great! Thank you for taking the time to rig the models and set up the profile.

**Comment by song-fangzhen** [comment]
Hi, @toji.
May I ask when the assets on [CDN](https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets@1.0/dist/profiles/) will be updated \
 so that any browsers/websites that want to use the latest modes can make a test with them?

**Comment by toji** [comment]
Thanks for the reminder. I will try to push that today.

**Comment by toji** [comment]
Published: https://www.npmjs.com/package/@webxr-input-profiles/assets

**Pull request merged**
