### PR TITLE
Add YVR Touch controller models and profiles

### PR DESCRIPTION
**Pull request by muxiaozi**

### CODE REVIEW

**Comment by muxiaozi** [comment]
@toji Could you merge it please?

**Comment by muxiaozi** [comment]
@toji If you have any questions about this PR, please raise them without any concerns.

**Comment by toji** [comment]
Apologies for the slow review, been on vacation.

Validated locally and found that all of the motion bindings appear to be functioning as expected and that there's no obvious defects in the models. Great job preparing these assets! I'll merge it once the CI checks have completed.

**Comment by toji** [comment]
The check failure has nothing to do with your PR, I need to fix a permissions issue internally. I'll land this once I've done that.

**Pull request merged**
