### PR TITLE
Added profile and assets for oculus-touch-v3 (Quest 2) controllers

### PR DESCRIPTION
**Pull request by toji**
Adds profile and assets for the Oculus Quest 2 controllers. Assets pulled from https://developer.oculus.com/downloads/package/oculus-controller-art/ and touched up/rigged by myself in Blender.

@Artyom17 or @cabanier, can you approve given that these are for an Oculus product?

### CODE REVIEW

**Comment by toji** [comment]
Preview of the controller assets in the viewer:

Screenshot 2020-10-15 184802

**Comment by cabanier** [comment]
We've been working on our own glb's and are about ready to share them.
However, there is currently a bug in the oculus browser where it reports v3 controllers even on Quest. We have fixed this on our side but that version hasn't rolled out yet.
Until that happens, we shouldn't post v3 controllers because then Quest users will get the wrong assets.

**Comment by toji** [comment]
Good to hear you've been working on it! Feel free to compare your assets with what I've posted here and if you feel that yours is a better representation for any reason I'll happily merge them instead!

In terms of timing, we could merge the new assets into this repo right away but only push it to npm (which populates the most commonly used CDN) when your browser fix has been pushed.

**Comment by cabanier** [comment]
We compared our new assets with yours and we think that ours have a higher quality.
I will see if we can do a PR.

**Comment by toji** [comment]
Not surprised. :) Looking forward to seeing your PR, and I'll leave this here (as a draft so it doesn't accidentally get merged) just in case it's helpful to reference anything from it.

**Comment by toji** [comment]
Closed by merging Oculus-provided assets in #183

**Pull request closed without merging**
