### PR TITLE
Adding profile and assets for meta-quest-touch-pro (Meta Quest Pro) controllers

### PR DESCRIPTION
**Pull request by felixtrz**
Adds profile and assets for meta-quest-touch-pro controllers @toji @cabanier

### CODE REVIEW

**Comment by cabanier** [comment]
Thanks for posting this @felixtrz !
@toji , the Quest Controller Pro has some new features that don't quite fit with the standard input profile. Can we discuss how to best describe them?

**Comment by toji** [comment]
Tested locally, looks great! Thanks! I'll publish a new version of the assets package today, and we can discuss the new functionality further on the calls.

**Comment by cabanier** [comment]
It seems the controller is not listed on `https://immersive-web.github.io/webxr-input-profiles/packages/viewer/dist/index.html`. Is there another file that needs to be updated?

**Comment by toji** [comment]
Published!

**Comment by toji** [comment]
The viewer just

> It seems the controller is not listed on `https://immersive-web.github.io/webxr-input-profiles/packages/viewer/dist/index.html`. Is there another file that needs to be updated?

The viewer just takes a bit to roll, and the github pages can be a little aggressive about caching. It should show up Real Soon Now.

**Comment by felixtrz** [comment]
Awesome! Thank you @toji for acting on this so promptly!

**Pull request merged**
